development:
  adapter: postgresql
  encoding: unicode
  database: miditopia_development
  pool: 5
  username: <%= ENV['USER'] %>
  password:
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: miditopia_test
  pool: 5
  username: <%= ENV['USER'] %>
  password:
  min_messages: warning
